PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

# Custom prefixes
PREFIX base: <http://webprotege.stanford.edu/>

# Patterns
SELECT ?subject WHERE {
  # Pattern for querying using the subClassOf. 
  # base:Density is the argument
  # subject is the result
  ?subject rdf:type owl:Class .
  ?subject rdfs:subClassOf base:Density .
}

SELECT ?subject WHERE {
  # Pattern for querying using the custom property hasInput. 
  # base:LAMMPSLog is the argument.
  # ?subject is the result.
  ?subject rdf:type owl:Class .
  ?subject rdfs:subClassOf ?restriction .
  ?restriction rdf:type owl:Restriction .
  ?restriction owl:onProperty base:hasInput .
  ?restriction owl:someValuesFrom base:LAMMPSLog .
}

SELECT ?subject WHERE {
  # Pattern for querying using the custom property hasOutput. 
  # base:LAMMPSLog is the argument.
  # ?subject is the result.
  ?subject rdf:type owl:Class .
  ?subject rdfs:subClassOf ?restriction .
  ?restriction rdf:type owl:Restriction .
  ?restriction owl:onProperty base:hasOutput .
  ?restriction owl:someValuesFrom base:FluidDensity .
}

SELECT ?object WHERE {
  # Inverting the result with the argument the results the patterns makes an inversion of responsibility
  # Example with hasInput
  # ?object is the result
  base:MoltemplateProcess1 rdf:type owl:Class .
  base:MoltemplateProcess1 rdfs:subClassOf ?restriction .
  ?restriction rdf:type owl:Restriction .
  ?restriction owl:onProperty base:hasInput .
  ?restriction owl:someValuesFrom ?object .
}

SELECT ?subject WHERE {
  # Pattern for finding an individual of a class
  # Example: individual of MoltemplateProcess1
  # ?subject is the result.
  ?subject rdf:type base:MoltemplateProcess1, owl:NamedIndividual .
}
