Step:
  steptype: FUNCTION
  output_iri: http://emmo.info/emmo#FluidDensity
  output_unit: None
  cost: 10.0
  routes:
    - arg1:
        steptype: FUNCTION
        output_iri: http://emmo.info/emmo#LAMMPSLog
        output_unit: None
        cost: 10.0
        routes:
          - arg1:
              steptype: UNSPECIFIED
              output_iri: http://emmo.info/emmo#LAMMPSArguments
              output_unit: None
              cost: 1.0
              routes:
            arg2:
              steptype: FUNCTION
              output_iri: http://emmo.info/emmo#LAMMPSDataSetInput
              output_unit: None
              cost: 10.0
              routes:
                - arg1:
                    steptype: FUNCTION
                    output_iri: http://emmo.info/emmo#LTFluidDensityMaster
                    output_unit: None
                    cost: 10.0
                    routes:
                      - arg1:
                          steptype: UNSPECIFIED
                          output_iri: http://emmo.info/emmo#LTFluidDensityTemplate
                          output_unit: None
                          cost: 1.0
                          routes:
                        arg2:
                          steptype: UNSPECIFIED
                          output_iri: http://emmo.info/emmo#userPressure
                          output_unit: None
                          cost: 1.0
                          routes:
                        arg3:
                          steptype: UNSPECIFIED
                          output_iri: http://emmo.info/emmo#userTemperature
                          output_unit: None
                          cost: 1.0
                          routes:
                        arg4:
                          steptype: UNSPECIFIED
                          output_iri: http://emmo.info/emmo#waterDensityParametersInput
                          output_unit: None
                          cost: 1.0
                          routes:
                  arg2:
                    steptype: UNSPECIFIED
                    output_iri: http://emmo.info/emmo#MoltemplateArguments
                    output_unit: None
                    cost: 1.0
                    routes:
                  arg3:
                    steptype: UNSPECIFIED
                    output_iri: http://emmo.info/emmo#pipelineMoltemplateDependency
                    output_unit: None
                    cost: 1.0
                    routes: